### ISSUE TITLE
update to your script

### ISSUE THREAD

**Issue by crshnbrn66** [hnky/VSTS-Deploy-AppSettings#3]
Hank. 

I have a script that I wrote that uses the same type things you are doing with Appsettings.  

Here is that script: 

`param($websitename = 'SchuTestApp' ,$resourceGroup = 'SchuTest',$slot = 'production', $appSettings ='{"AppSettings:testkey1":  "45test","AppSettings:TestId":  "This is a Test Key 28"}')
#https://stackoverflow.com/questions/8800375/merging-hashtables-in-powershell-how
Function Merge-Hashtables([ScriptBlock]$Operator) {
    $Output = @{}
    ForEach ($Hashtable in $Input) {
        If ($Hashtable -is [Hashtable]) {
            ForEach ($Key in $Hashtable.Keys) {$Output.$Key = If ($Output.ContainsKey($Key)) {@($Output.$Key) + $Hashtable.$Key} Else  {$Hashtable.$Key}}
        }
    }
    If ($Operator) {ForEach ($Key in @($Output.Keys)) {$_ = @($Output.$Key); $Output.$Key = Invoke-Command $Operator}}
    $Output
}
try {
    ConvertFrom-Json $appSettings -ErrorAction Stop
    #it is expected that the app settings is a string representation of a hashtable that is writtin in Json.  So that it can be converted to a powershell hashtable during runtime
    $newAppSettings = $appSettings | convertfrom-json 
    $newAppSettingsHash = @{}
    $newAppSettings.psobject.properties | ForEach-Object { $newAppSettingsHash[$_.Name] = $_.Value } 
    $Application = get-azurermwebappslot -Name $websitename -ResourceGroupName $resourceGroup -Slot $slot
    $ExistingSettings = $Application.siteconfig.AppSettings
    $appSettingsHash = @{}
    foreach($k in $ExistingSettings)
    {
        $appSettingsHash[$k.name] = $k.value
    }
    #https://stackoverflow.com/questions/8800375/merging-hashtables-in-powershell-how
    $hashtable = $newAppSettingsHash, $appSettingsHash | Merge-Hashtables {$_[0]}
    $results = Set-AzureRmWebAppSlot -AppSettings $hashtable -name $websitename -ResourceGroupName $resourceGroup -slot $slot
    $r = $results.SiteConfig.AppSettings
    Write-Output $r
} 
catch 
{
    Write-Error "$appsettings must be in JSON format"
}`
Hopefully this helps.

**Comment by ceituna** [comment]
Thanks, but can you please format the code? And how is this different from the current code in the extension? It's a bit difficult now to analyze the code.
